### ISSUE TITLE
BUG: File upload fails if full path is used and file is not in CWD

### ISSUE THREAD

**Issue by naveenragur** [neptune-ai/neptune-sacred#24]
### Describe the bug
When adding artifact with filename as full path, the filname is extracted and before upload the current wd path + filename is used to upload as seen below in neptune_sacred/impl/__init__.py

    def artifact_event(self, name, filename, metadata=None, content_type=None):
        filename = os.path.split(filename)[-1]
        self._run[self.base_namespace][f"io_files/artifacts/{name}"].upload(filename)

this causes error for upload as below:

ERROR - neptune.internal.operation_processors.async_operation_processor - Error occurred during asynchronous operation processing: Cannot upload file "current_wd_path/filename": Path not found or is a not a file.

### Expected behavior
No error and it should upload to neptune and visible to use in dashboard etc

### Solution
remove line 139 #filename = os.path.split(filename)[-1]

**Comment by SiddhantSadangi** [comment]
Hello @naveenragur 👋 

I was able to reproduce the issue and will forward this to the developers. Thanks for reporting this 🙏 

While we release a fix, can you make the changes in your local system and see if it works as expected?

**Comment by SiddhantSadangi** [comment]
Hey @naveenragur 👋 

We just released [`neptune-sacred v1.0.1`](https://github.com/neptune-ai/neptune-sacred/releases/tag/1.0.1), which fixes this issue 🎉 

Can you let me know if this works? And thanks again for reporting this! 🙏
