### ISSUE TITLE
Feature Request: Accept dictionaries/lists as values in the result dictionary

### ISSUE THREAD

**Issue by wl2522** [neptune-ai/neptune-sacred#8]
### Is your feature request related to a problem? Please describe.

At the moment, my model training script returns a nested dictionary at the end of model training with Sacred. This causes the following error:

```
  File "C:\ProgramData\Anaconda3\envs\item_prediction\lib\site-packages\sacred\run.py", line 429, in _final_call
    getattr(observer, method)(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\item_prediction\lib\site-packages\neptune_sacred\impl\__init__.py", line 117, in completed_event
    self._run[self.base_namespace][f'metrics/results/{k}'].upload(v)
  File "C:\ProgramData\Anaconda3\envs\item_prediction\lib\site-packages\neptune\new\handler.py", line 139, in upload
    value = FileVal.create_from(value)
  File "C:\ProgramData\Anaconda3\envs\item_prediction\lib\site-packages\neptune\new\types\atoms\file.py", line 252, in create_from
    raise TypeError("Value of type {} is not supported.".format(type(value)))
TypeError: Value of type <class 'dict'> is not supported.
```

### Describe the solution you'd like

It would be great if the `completed_event()` method includes an `elif isinstance(v, list) or isinstance(v, dict):` clause that converts those values to strings using `json.dumps()` (which is how `SlackObserver` in the Sacred library handles this situation). 

### Describe alternatives you've considered

I understand that I could just manually convert each  dictionary/list to JSON as they're being added to the result dictionary, but I think that shouldn't be necessary because nested result dictionaries are natively supported in Sacred because the result dictionary is simply added as a value in `run.json` at the end of model training. I was also able to use nested result dictionaries in the `neptune-contrib` version of `NeptuneObserver` without any errors.

**Comment by Raalsky** [comment]
Thank you @wl2522 for all of your attention and work. We will publish soon your updates (I think it will happen in next week) right after we figure out last of issues that you already submitted.
